---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

inputs:
  - name: cf-networking-release
  - name: input_repo
  - name: source

outputs:
  - name: output_repo

params:
    SOURCE_FILE: ~
    DEST_SUFFIX: ~

run:
  path: cf-networking-release/ci/cf-networking-ci/tasks/commit-new-file
