---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
- name: cf-networking
- name: version
- name: cf-networking-release

outputs:
- name: tarballs

run:
  path: cf-networking-release/ci/cf-networking-ci/tasks/create-release-tarball

params:
  RELEASE_NAME: cf-networking
