---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-mysql-5.6 }

platform: linux

inputs:
- name: cf-networking-release

run:
  path: cf-networking-release/scripts/unit-and-integration-tests.sh

params:
  GINKGO_EXTRA_FLAGS: "-race"
  DB: mysql-5.6
