---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/small-git }

inputs:
  - name: cf-networking-release

outputs:
  - name: docker-image-tag-path

params:
  TAG: latest

run:
  path: cf-networking-release/ci/cf-networking-ci/tasks/set-docker-image-tag

