platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

inputs:
  - name: cf-networking-release-ci
  - name: deployments-repo
  - name: scaling-test-params

outputs:
  - name: test-config

params:
  ENVIRONMENT_NAME: ~

run:
  path: cf-networking-release-ci/ci/cf-networking-ci/tasks/set-scaling-test-params
