---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: version
  - name: cf-networking-release-ci
  - name: cf-networking-deployments
  - name: cf-networking-tarball
  - name: cf-networking
  - name: cf-networking-master

outputs:
  - name: final-release
  - name: release

run:
  path: cf-networking-release-ci/ci/cf-networking-ci/tasks/shipit
