---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking-release
  - name: test-config
  - name: cf-networking

outputs:
  - name: network-stats

params:
    ENVIRONMENT_NAME: ~

run:
  path: cf-networking-release/ci/cf-networking-ci/tasks/test-scalability
