---
platform: linux

image_resource:
  type: docker-image
  source: { repository: alpine}

inputs:
- name: golang-1.x-tarball
- name: dockerfile

outputs:
- name: docker-build-context

params:
  INPUT_DOCKERIMAGE_PATH: Dockerfile

run:
  path: sh
  args:
  - -exuc
  - |
    cp $INPUT_DOCKERIMAGE_PATH/* docker-build-context
    cp golang-1.x-tarball/go* docker-build-context
