---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/small-git }

platform: linux

inputs:
  - name: cf-networking-ci
  - name: cf-deployment
  - name: deployments-repo
  - name: cf-networking-release

outputs:
  - name: ops-files

run:
  path: cf-networking-ci/ci/tasks/collect-ops-files

params:
  ENVIRONMENT_NAME: ~
