---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

params:
  ENVIRONMENT: ~

inputs:
  - name: cf-networking-ci
  - name: cf-networking-deployments

outputs:
  - name: integration-config

run:
  path: cf-networking-ci/ci/tasks/copy-config
