---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy, tag: '0.6.0'  }

platform: linux

params:
  ENVIRONMENT: ~

inputs:
  - name: cf-networking-release-ci
  - name: cf-networking-deployments

outputs:
  - name: integration-config

run:
  path: cf-networking-release-ci/ci/tasks/copy-config
