---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
- name: my-release
- name: version
- name: cf-networking-release-ci

outputs:
- name: tarballs

run:
  path: cf-networking-release-ci/ci/tasks/create-release-tarball

params:
  RELEASE_NAME: cf-networking
