---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

inputs:
  - name: cf-networking-release-ci
  - name: test-config
  - name: vars-store
  - name: variables

outputs:
  - name: drats-integration-config

params:
  ENVIRONMENT_NAME: ~

run:
  path: cf-networking-release-ci/ci/tasks/create-drats-config
