---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy-light }

inputs:
  - name: cf-networking-release-ci
  - name: deployments-repo

params:
  ENVIRONMENT_NAME: ~
  VARS_STORE: "../ci/vars-store.yml"

run:
  path: cf-networking-release-ci/ci/tasks/deploy-bbr-concourse-worker
