---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: cf-networking-ci
  - name: cf-networking-dev
  - name: cf-networking-master

outputs:
  - name: release-merged

run:
  path: cf-networking-ci/ci/tasks/merge-master
