---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/deploy }

platform: linux

inputs:
  - name: version
  - name: cf-networking-release-ci
  - name: cf-networking


run:
  path: cf-networking-release-ci/ci/tasks/shipit
