---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking-ci
  - name: test-config
  - name: cf-networking

params:
    ENVIRONMENT_NAME: ~
    ENVIRONMENT_TAG: ~
    CONFIG: ~

run:
  path: cf-networking-ci/ci/tasks/smoke-tests
