---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking
  - name: test-config

params:
    ENVIRONMENT_NAME: ~
    ENVIRONMENT_TAG: ~
    CONFIG: ~
    DATADOG_API_KEY: ~

run:
  path: cf-networking/ci/tasks/smoke-tests-sd
