---
image_resource:
  type: docker-image
  source:
    repository: c2cnetworking/deploy
    tag: latest

platform: linux

inputs:
  - name: cf-deployment-concourse-tasks
  - name: cf-networking-release-ci
  - name: env-repo
  - name: local-release

run:
  path: cf-networking-release-ci/ci/tasks/upload-local-release

params:
  BBL_STATE_DIR:
