---
platform: linux

image_resource:
  type: docker-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking-release-ci
  - name: variables

params:
    SYSTEM_DOMAIN: ~
    ENVIRONMENT_NAME: ~

run:
  path: cf-networking-release-ci/ci/tasks/verify-api-ready
