---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/small-git }

platform: linux

inputs:
  - name: cf-networking-release-ci
  - name: master-release
  - name: other-release-version

outputs:
  - name: release-notes

run:
  path: cf-networking-release-ci/ci/tasks/build-release-notes/task

params:
  SOURCE_DIR: master-release
  OUTPUT_DIR: release-notes
  OTHER_RELEASE_NAME: silk-release
  PRE_RELEASE: "false"
  TRACKER_API_TOKEN:
