---
platform: linux

image_resource:
  type: registry-image
  source: { repository: c2cnetworking/dev-postgres }

inputs:
  - name: cf-networking-release-ci
  - name: test-config
  - name: cf-networking

outputs:
  - name: network-stats

params:
    TEST_CONFIG_DIR: ~

run:
  path: cf-networking-release-ci/ci/tasks/test-scalability/task
