---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/small-git }

platform: linux

inputs:
  - name: cf-networking-release-ci
  - name: master-release
  - name: other-release-version

run:
  path: cf-networking-release-ci/ci/tasks/print-bosh-job-diff/task

params:
  SOURCE_DIR: master-release
  PRE_RELEASE: "false"
